// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLunI7EjgKQcenG8GJ8WNpQElmOoF-psM',
    appId: '1:668937141025:web:6d633c039944450d9b9c60',
    messagingSenderId: '668937141025',
    projectId: 'chat-app-cf7cd',
    authDomain: 'chat-app-cf7cd.firebaseapp.com',
    storageBucket: 'chat-app-cf7cd.appspot.com',
    measurementId: 'G-4N062NWJMP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAX3nvGADOXH58bvx81Qf_94jcCgHRoagM',
    appId: '1:668937141025:android:9832ee8633e514c99b9c60',
    messagingSenderId: '668937141025',
    projectId: 'chat-app-cf7cd',
    storageBucket: 'chat-app-cf7cd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMOBnafWjvGHuke6etzU3LhI5jwqZ8U_E',
    appId: '1:668937141025:ios:4992126dc656e2479b9c60',
    messagingSenderId: '668937141025',
    projectId: 'chat-app-cf7cd',
    storageBucket: 'chat-app-cf7cd.appspot.com',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAMOBnafWjvGHuke6etzU3LhI5jwqZ8U_E',
    appId: '1:668937141025:ios:4992126dc656e2479b9c60',
    messagingSenderId: '668937141025',
    projectId: 'chat-app-cf7cd',
    storageBucket: 'chat-app-cf7cd.appspot.com',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBLunI7EjgKQcenG8GJ8WNpQElmOoF-psM',
    appId: '1:668937141025:web:6f055f26983de1f89b9c60',
    messagingSenderId: '668937141025',
    projectId: 'chat-app-cf7cd',
    authDomain: 'chat-app-cf7cd.firebaseapp.com',
    storageBucket: 'chat-app-cf7cd.appspot.com',
    measurementId: 'G-JBQK18STDP',
  );
}
